pipeline {
    agent {
        node {
            label 'maven'
        }
    }

    stages {
        stage('Clone Code') {
            steps {
                echo "Source code is already checked out by Jenkins"
            }
        }

        stage('Set Working Directory') {
            steps {
                dir('source-code') {
                    echo "Now inside the source-code directory"
                }
            }
        }

        stage('build') {
            steps {
                sh 'mvn clean deploy'
            }

        }




    }
}
