pipeline {
    agent {
        node {
            label 'maven'
        }
    }

    stages {
        stage('Clone-repo') {
            steps {
                git branch: 'main', url: 'https://github.com/ITNaveen/jenkins-tools_installation.git'
            }
        }
        stage('Set Working Directory') {
            steps {
                dir('source-code') {
                    echo "Now inside the source-code directory"
                }
            }
        }
    }
}
